class_name LevelData
extends Resource

## One of the eight Chuckie Egg layouts, converted from the BBC level tables.
##
## Every coordinate here is in BBC tile space: 20 columns by 25 rows, y-up with
## y = 0 at the bottom. Convert to Godot's y-down space when placing tiles —
## see LevelMap and Playfield.
##
## Generated by tools/leveldata_to_tres.py from the reference implementation's
## leveldata.c. Edit the generator, not the .tres files.

## Horizontal platforms as (y, x_start, x_end), inclusive at both ends.
@export var walls: Array[Vector3i] = []

## Vertical ladders as (x, y_start, y_end), inclusive at both ends.
@export var ladders: Array[Vector3i] = []

## Whether this layout has the paired lifts. True for layouts 3-7.
@export var have_lift: bool = false

## Tile column shared by both lifts. Meaningless unless have_lift.
@export var lift_x: int = 0

## Egg positions. Always exactly 12.
@export var eggs: Array[Vector2i] = []

## Grain positions. Count varies per layout.
@export var grain: Array[Vector2i] = []

## Hen spawn tiles. Always 5 are stored even when fewer hens are used.
@export var hen_starts: Array[Vector2i] = []

## Hen count from the level table. The round rules in GameState override this:
## round 2 has none, and level 24 onwards always uses all 5.
@export var base_hen_count: int = 0
